Added test
AbstractSDK/carrot-app pull request #14
Opened 2024-02-16 19:05 UTC by Kayanski

This PR aims at adding a simple test for double create-position to make sure the position is succesfully created even after a second creation.

## Issue

The logic is not perfect because the position is not recomputed according to the actual funds distribution after withdraw and instead is a little off. 

Creating a large position to simulate the actual pool weight might change that

2024-02-19 10:08 UTC, Buckram123 requested changes
Would be nice to see a test with 0funds second create_position for readjusting position

2024-02-26 09:01 UTC, Kayanski commented on contracts/savings-app/tests/edge_cases.rs
> +}
Sorry, I thought you told me you didn't have tests for this case, so I wrote one more? deleting and replacing with 0funds create position

2024-02-26 09:07 UTC, Buckram123 commented on contracts/savings-app/tests/edge_cases.rs
> +}
> Sorry, I thought you told me you didn't have tests for this case, so I wrote one more?

Sorry, this test was written before position recomputing logic was added, I only adjusted this slightly after the change. Was not sure if more testing on that required!

2024-03-11 15:38 UTC, CyberHoward commented
@Buckram123 could you finish this PR or close it (if the test it adds are already in place)?

2024-03-12 09:24 UTC, Buckram123 commented
We disallow position re-creation, introduced by #29

2024-03-12 09:24 UTC, closed without merging